# Generated by Django 4.2.7 on 2025-11-02 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_paymentgateway_withdrawalrequest_exchangerate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.CharField(choices=[('NGN', 'Nigerian Naira'), ('KES', 'Kenya Shilling'), ('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('USDT', 'Tether USD')], max_length=10),
        ),
    ]
