# Generated by Django 4.2.7 on 2025-11-03 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_wallet_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='deposit_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
